### ISSUE TITLE
install guide?

### ISSUE THREAD

**Issue by killmasta93** [davidedc/QR-and-JIRA-check-in-check-out-system#1]
Hi 
Currently trying to install but im somewhat lost i try looking at http://jira-python.readthedocs.org/ but it gives the not found page. 
Also how does it save all the info? do i need to install mysql?
Thank you

**Comment by davidedc** [comment]
Hi - the link should probably be changed to https://jira.readthedocs.io/en/master/ .
The info are saved in JIRA - so as long as you have JIRA you'll be fine!

Cheers!
D
